name: Replace URLS

on:
    push:
        branches: [ "main" ]
jobs:
  replacelinks:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: "Find and Replace BP links"
          uses: jacobtomlinson/gha-find-replace@v3
          with:
            find: "([A-Za-z0-9])\\w+\\.html|([A-Za-z0-9])\\w+[-_]\\S+\\.html"
            replace: 'BP/$&'
            regex: true
            include: "BP/**/*.md"
        - name: Push changes
          uses: stefanzweifel/git-auto-commit-action@v4