name: Replace Videos
on:
  workflow_call:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "video#"
          replace: '<video width="320" height="240" controls><source src="'
          regex: false
          include: "**README.md"
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "#video"
          replace: '" type="video/mp4">Your browser does not support the video tag.</video>'
          regex: false
          include: "**README.md"
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
