name: Replace_Links

on:
  # Runs on pushes targeting the default branch
  pull_request:
    types: 
      - closed
    branches:
      - 'main'

jobs:
    find-replace:
      runs-on: ubuntu-latest

      steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Find and replace links in BP
        run: |
            find BP -name "*.md" -type f -exec sed -i -E 's#\((https://ewildingli\.github\.io/Global-Instructor-Guidelines/((?!BP/)[A-Za-z0-9_-]+)\.html)\)#\((https://ewildingli.github.io/Global-Instructor-Guidelines/BP/\2.html)\)#g' {} +
      - name: Find and replace links in DE
        run: |
            find DE -name "*.md" -type f -exec sed -i -E 's#\((https://ewildingli\.github\.io/Global-Instructor-Guidelines/((?!DE/)[A-Za-z0-9_-]+)\.html)\)#\((https://ewildingli.github.io/Global-Instructor-Guidelines/DE/\2.html)\)#g' {} +
    
      - name: Find and replace links in ES
        run: |
            find ES -name "*.md" -type f -exec sed -i -E 's#\((https://ewildingli\.github\.io/Global-Instructor-Guidelines/((?!ES/)[A-Za-z0-9_-]+)\.html)\)#\((https://ewildingli.github.io/Global-Instructor-Guidelines/ES/\2.html)\)#g' {} +
    
      - name: Find and replace links in FR
        run: |
            find FR -name "*.md" -type f -exec sed -i -E 's#\((https://ewildingli\.github\.io/Global-Instructor-Guidelines/((?!FR/)[A-Za-z0-9_-]+)\.html)\)#\((https://ewildingli.github.io/Global-Instructor-Guidelines/FR/\2.html)\)#g' {} +
    
      - name: Push_changes
        uses: stefanzweifel/git-auto-commit-action@v4

