name: GPT Translate per Commit
 
on:
  workflow_call:
jobs:
  gpt_translate:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout repository with two latest commits
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
 
      - name: get changed files name
        id: changed_files
        run: |
          echo "git diff --name-only HEAD^ HEAD | grep '\.md$' | tr '\n' ' '"
          echo "FILES=$(git diff --name-only HEAD^ HEAD | grep '\.md$' | tr '\n' ' ')" >> $GITHUB_ENV
          
      - name: Run GPT Translate BP
        uses: 3ru/gpt-translate@master
        with:
          apikey: ${{ secrets.OPENAI_API_KEY }}
          provider: 'openai'
          model: 'gpt-4o-mini'
          inputFiles: ${{ env.FILES }}
          outputFiles: 'BP/**/*.md'
          languages: 'Portuguese'
          
      - name: Run GPT Translate DE
        uses: 3ru/gpt-translate@master
        with:
          apikey: ${{ secrets.OPENAI_API_KEY }}
          provider: 'openai'
          model: 'gpt-4o-mini'
          inputFiles: ${{ env.FILES }}
          outputFiles: 'DE/**/*.md'
          languages: 'German'
          
      - name: Run GPT Translate ES
        uses: 3ru/gpt-translate@master
        with:
          apikey: ${{ secrets.OPENAI_API_KEY }}
          provider: 'openai'
          model: 'gpt-4o-mini'
          inputFiles: ${{ env.FILES }}
          outputFiles: 'ES/**/*.md'
          languages: 'Spanish'

      - name: Run GPT Translate FR
        uses: 3ru/gpt-translate@master
        with:
          apikey: ${{ secrets.OPENAI_API_KEY }}
          provider: 'openai'
          model: 'gpt-4o-mini'
          inputFiles: ${{ env.FILES }}
          outputFiles: 'FR/**/*.md'
          languages: 'French'
