name: GPT Translate per Commit
 
on:
  push:
    branches:
      - main
jobs:
  gpt_translate:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout repository with two latest commits
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
 
      - name: Get all changed markdown files
          id: changed_files
          uses: tj-actions/changed-files@v45
          with:
            # Avoid using single or double quotes for multiline patterns
            files: |
              **.md

      - name: Run GPT Translate BP
        uses: 3ru/gpt-translate@master
        with:
          apikey: ${{ secrets.OPENAI_API_KEY }}
          provider: 'openai'
          model: 'gpt-4o-mini'
          inputFiles: ${{ steps.changed_files.outputs.files }}
          outputFiles: 'BP/**/*.md'
          languages: 'Portuguese'

      - name: Run GPT Translate DE
        uses: 3ru/gpt-translate@master
        with:
          apikey: ${{ secrets.OPENAI_API_KEY }}
          provider: 'openai'
          model: 'gpt-4o-mini'
          inputFiles: ${{ steps.changed_files.outputs.files }}
          outputFiles: 'DE/**/*.md'
          languages: 'German'

      - name: Run GPT Translate ES
        uses: 3ru/gpt-translate@master
        with:
          apikey: ${{ secrets.OPENAI_API_KEY }}
          provider: 'openai'
          model: 'gpt-4o-mini'
          inputFiles: ${{ steps.changed_files.outputs.files }}
          outputFiles: 'ES/**/*.md'
          languages: 'Spanish'

      - name: Run GPT Translate FR
        uses: 3ru/gpt-translate@master
        with:
          apikey: ${{ secrets.OPENAI_API_KEY }}
          provider: 'openai'
          model: 'gpt-4o-mini'
          inputFiles: ${{ steps.changed_files.outputs.files }}
          outputFiles: 'FR/**/*.md'
          languages: 'French'
